/** Dream symbol locale data: Animals + Nature */
export const POLISH_ANIMALS_NATURE_EN = [
  // Animals
  {
    keywords: ['蛇', '蟒蛇', '毒蛇', 'snake', 'python', 'viper'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Shedding, renewal, and hidden change.',
    interpretationEn:
      'In traditional symbolism, the snake points to transformation and spiritual awakening. In depth psychology, it often represents life force and the shadow self that has not yet been integrated. Dreaming of a snake usually suggests that deep inner change is already underway, even if it is still happening below the surface.',
    positiveEn: 'A new layer of insight is emerging as an old self begins to fall away.',
    negativeEn: 'A hidden risk or unspoken tension may still be waiting in the background.',
    adviceEn: 'Stay observant and notice subtle changes in people, patterns, and emotions before reacting.',
    themesEn: ['Transformation', 'Wisdom', 'Hidden tension'],
  },
  {
    keywords: ['龙', '神龙', '飞龙', 'dragon', 'flying dragon'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Power, blessing, and rising destiny.',
    interpretationEn:
      'The dragon is a noble creature associated with authority, fortune, and a larger force moving through your life. Psychologically, it can symbolize ambition and creative power that has been held back for too long. Its appearance often means your deeper potential wants to step into the open.',
    positiveEn: 'Opportunity and momentum are gathering around your larger aspirations.',
    negativeEn: 'Pride, pressure, or overreaching may turn strength into strain.',
    adviceEn: 'Choose one meaningful goal and support your ambition with steady, grounded effort.',
    themesEn: ['Power', 'Blessing', 'Ambition'],
  },
  {
    keywords: ['鱼', '金鱼', '大鱼', '小鱼', 'fish', 'goldfish', 'big fish', 'small fish'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Abundance, intuition, and emerging opportunity.',
    interpretationEn:
      'Fish are linked with prosperity and also with the richness of the unconscious mind. A fish or school of fish in dreams often signals that emotional insight, luck, or useful opportunities are rising toward awareness.',
    positiveEn: 'Helpful chances and inner guidance are beginning to surface.',
    negativeEn: 'Hesitation may let a promising opening slip away.',
    adviceEn: 'Pay attention to small details and quiet signals. They may lead to something larger.',
    themesEn: ['Abundance', 'Intuition', 'Opportunity'],
  },
  {
    keywords: ['猫', '黑猫', '白猫', 'cat', 'black cat', 'white cat'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Instinct, mystery, and personal boundaries.',
    interpretationEn:
      'Cats often point to intuition, independence, and sensitivity to what is unspoken. They move between closeness and distance with ease, so dreaming of a cat can reflect your own shifting needs for intimacy, privacy, and trust.',
    positiveEn: 'Your instincts can guide you around confusion and toward clarity.',
    negativeEn: 'Too much distance may keep others from truly reaching you.',
    adviceEn: 'Trust your first impression, but leave space for safe connection as well.',
    themesEn: ['Intuition', 'Independence', 'Mystery'],
  },
  {
    keywords: ['狗', '小狗', '大狗', 'dog', 'puppy', 'big dog'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Loyalty, protection, and human warmth.',
    interpretationEn:
      'Dogs symbolize loyalty, companionship, and protective instinct. Whether the dog is barking, following, or staying close, the dream often reflects support systems, trust, and the feeling that you do not have to face everything alone.',
    positiveEn: 'Reliable support and sincere care may already be around you.',
    negativeEn: 'Depending too much on outside reassurance can weaken your own confidence.',
    adviceEn: 'Strengthen bonds with trustworthy people and offer loyalty where it matters.',
    themesEn: ['Loyalty', 'Protection', 'Friendship'],
  },
  {
    keywords: ['鸟', '飞鸟', '小鸟', '大鸟', '鸟群', 'bird', 'flying bird', 'flock', 'small bird'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Freedom, messages, and higher vision.',
    interpretationEn:
      'Birds are often linked with freedom, news from afar, and the desire to rise above limitation. A single bird or a flock may reflect your longing for expansion, perspective, or movement toward a more open state of mind.',
    positiveEn: 'Fresh perspective and welcome news may be on the way.',
    negativeEn: 'Idealism without grounding can leave your plans floating in the air.',
    adviceEn: 'Keep one foot on practical ground while allowing your mind to look farther ahead.',
    themesEn: ['Freedom', 'Messages', 'Transcendence'],
  },
  {
    keywords: ['老虎', '猛虎', '虎', 'tiger'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Courage, raw force, and commanding presence.',
    interpretationEn:
      'The tiger represents power, instinct, and situations that require bravery. It may point to a challenge that cannot be avoided, or to a strong part of yourself that is ready to stop shrinking and take up space.',
    positiveEn: 'You may have more courage and presence than you realize.',
    negativeEn: 'Aggression, fear, or reckless confrontation could make things harsher than needed.',
    adviceEn: 'Use intelligence to guide strength. Observe first, then act decisively.',
    themesEn: ['Courage', 'Authority', 'Instinct'],
  },
  {
    keywords: ['马', '白马', '黑马', '骏马', 'horse', 'white horse', 'black horse', 'stallion'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Drive, freedom, and forward motion.',
    interpretationEn:
      'Horses often symbolize life force, momentum, and the urge to move ahead. A running horse suggests strong energy and ambition, while a restrained horse may reflect blocked progress or uncertain direction.',
    positiveEn: 'Your path may open quickly once your energy finds the right direction.',
    negativeEn: 'Speed without clarity can take you farther from what you actually want.',
    adviceEn: 'Name the destination before pushing harder. Direction matters as much as energy.',
    themesEn: ['Progress', 'Freedom', 'Momentum'],
  },
  {
    keywords: ['猪', '小猪', '大猪', 'pig', 'piglet', 'boar'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Comfort, plenty, and instinctive needs.',
    interpretationEn:
      'The pig is tied to material comfort, enjoyment, and the fulfillment of basic needs. In dreams, it can suggest a season of greater ease and abundance, but it may also warn against sinking too deeply into laziness or excess.',
    positiveEn: 'Stability, nourishment, and material ease may be growing.',
    negativeEn: 'Comfort could become stagnation if it replaces movement and purpose.',
    adviceEn: 'Enjoy what is good, but keep some energy reserved for what still needs building.',
    themesEn: ['Abundance', 'Pleasure', 'Instinct'],
  },
  {
    keywords: ['老鼠', '耗子', 'mouse', 'rat'],
    category: 'Animals',
    categoryKey: '动物',
    meaningEn: 'Survival, alertness, and nagging worries.',
    interpretationEn:
      'Mice and rats often symbolize small but persistent concerns, along with the cleverness needed to survive them. They may reflect anxiety about details, hidden problems, or a situation that feels more draining than dangerous.',
    positiveEn: 'Careful attention and flexibility can help you solve subtle problems.',
    negativeEn: 'Minor worries may multiply if they keep running loose in the background.',
    adviceEn: 'Write down the small concerns one by one and deal with them directly instead of carrying them mentally.',
    themesEn: ['Alertness', 'Details', 'Survival'],
  },

  // Nature
  {
    keywords: ['水', '大海', '河流', '湖泊', '洪水', '雨水', 'water', 'sea', 'ocean', 'river', 'lake', 'flood'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Emotion, depth, and inner flow.',
    interpretationEn:
      'Water is one of the clearest symbols for emotion and the unconscious. Calm water can reflect clarity and healing, while muddy or overwhelming water may point to confusion, emotional overload, or a feeling of losing control.',
    positiveEn: 'Emotional renewal and intuitive insight may be rising together.',
    negativeEn: 'Strong feelings could spill over if they are not acknowledged and held with care.',
    adviceEn: 'Slow down and regulate your inner state before trying to solve outward problems.',
    themesEn: ['Emotion', 'Unconscious', 'Flow'],
  },
  {
    keywords: ['火', '大火', '火焰', '燃烧', 'fire', 'flame', 'burning', 'blaze'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Passion, energy, and transformation.',
    interpretationEn:
      'Fire can symbolize vitality, desire, anger, or creative force. A contained fire often points to focused passion, while an uncontrolled blaze may show intensity that is becoming destructive or difficult to manage.',
    positiveEn: 'Your energy may be ready to break through stagnation and create movement.',
    negativeEn: 'Unchecked anger or obsession could burn through your balance and relationships.',
    adviceEn: 'Give strong feelings a clear outlet through creation, effort, or embodied action.',
    themesEn: ['Passion', 'Energy', 'Transformation'],
  },
  {
    keywords: ['山', '高山', '爬山', '山峰', 'mountain', 'peak', 'climb mountain'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Challenge, endurance, and higher goals.',
    interpretationEn:
      'Mountains symbolize effort, perspective, and meaningful obstacles. To dream of climbing or confronting a mountain often reflects a long-term goal, a serious test, or your relationship with difficulty itself.',
    positiveEn: 'Steady persistence can carry you much farther than force alone.',
    negativeEn: 'An overwhelming goal or isolated struggle may leave you depleted halfway through.',
    adviceEn: 'Break the bigger climb into smaller steps you can actually complete today.',
    themesEn: ['Challenge', 'Perseverance', 'Goals'],
  },
  {
    keywords: ['树', '大树', '森林', '树木', 'tree', 'forest', 'woods'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Growth, roots, and living continuity.',
    interpretationEn:
      'Trees often reflect family roots, long-term growth, and the structure that supports life over time. A strong tree suggests stability and healthy development, while a weakened tree may point to neglected foundations or disconnection from what sustains you.',
    positiveEn: 'Your roots and long-term growth may be strengthening quietly.',
    negativeEn: 'If the foundation is underfed, outer growth can become fragile.',
    adviceEn: 'Reconnect with the people, places, or practices that make you feel grounded.',
    themesEn: ['Growth', 'Roots', 'Life'],
  },
  {
    keywords: ['花', '花朵', '鲜花', '花海', 'flower', 'flowers', 'blossom', 'bouquet'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Beauty, tenderness, and fleeting bloom.',
    interpretationEn:
      'Flowers represent beauty, affection, freshness, and the briefness of certain moments. They may point to new feelings, emotional opening, or something precious that needs care while it is still blooming.',
    positiveEn: 'A relationship, idea, or phase of life may be opening in a beautiful way.',
    negativeEn: 'Fear of loss may keep you attached to appearances instead of real cultivation.',
    adviceEn: 'Enjoy what is blossoming, but also care for the soil beneath it.',
    themesEn: ['Beauty', 'Connection', 'New life'],
  },
  {
    keywords: ['月亮', '满月', '新月', '月光', 'moon', 'full moon', 'new moon', 'moonlight'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Intuition, cycles, and inner tides.',
    interpretationEn:
      'The moon is tied to intuition, sensitivity, changing moods, and cyclical inner life. Its phase in the dream can suggest whether something is ripening, receding, hidden, or ready to be seen more clearly.',
    positiveEn: 'Quiet intuition may be illuminating what logic alone could not reach.',
    negativeEn: 'Mood shifts and emotional tides may be stronger than usual.',
    adviceEn: 'Give yourself reflective time and notice what inner pattern is returning again.',
    themesEn: ['Intuition', 'Cycles', 'Emotion'],
  },
  {
    keywords: ['太阳', '阳光', '日出', '日落', 'sun', 'sunlight', 'sunrise', 'sunset'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Vitality, visibility, and conscious clarity.',
    interpretationEn:
      'The sun symbolizes life force, confidence, public presence, and conscious awareness. When it appears strongly in a dream, it often points to clarity, action, or a need to bring something into the open.',
    positiveEn: 'Confidence, visibility, and momentum may be increasing together.',
    negativeEn: 'Overexposure or excessive intensity could invite burnout or resistance.',
    adviceEn: 'Place important decisions in clear daylight, and be honest about what can now be seen.',
    themesEn: ['Vitality', 'Recognition', 'Consciousness'],
  },
  {
    keywords: ['雨', '下雨', '暴雨', '小雨', 'rain', 'rainfall', 'storm', 'drizzle'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Release, cleansing, and emotional weather.',
    interpretationEn:
      'Rain often symbolizes emotional release, cleansing, and changing atmosphere. Light rain may suggest quiet sadness or gentle renewal, while a storm can point to a stronger emotional turning point.',
    positiveEn: 'Built-up feelings may be clearing out and making room for something fresh.',
    negativeEn: 'Prolonged heaviness can slow both mood and movement if left unattended.',
    adviceEn: 'Let yourself release what is pressing on you instead of holding it in silence.',
    themesEn: ['Cleansing', 'Release', 'Change'],
  },
  {
    keywords: ['雪', '下雪', '雪花', '雪地', 'snow', 'snowflake', 'snowfield'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Stillness, purity, and emotional reserve.',
    interpretationEn:
      'Snow suggests quiet, cooling, and emotional distance, but also clarity and purity. It may reflect a time of retreat, preservation, or the need to let things settle before warmth and movement return.',
    positiveEn: 'A calm and reflective phase may help deeper planning and emotional settling.',
    negativeEn: 'Too much withdrawal could leave others feeling shut out.',
    adviceEn: 'Use solitude for honest reflection, but do not turn it into isolation.',
    themesEn: ['Stillness', 'Purity', 'Containment'],
  },
  {
    keywords: ['风', '大风', '狂风', '微风', 'wind', 'strong wind', 'storm wind', 'breeze'],
    category: 'Nature',
    categoryKey: '自然',
    meaningEn: 'Change, movement, and incoming signals.',
    interpretationEn:
      'Wind represents change that moves through a space without being fully visible. A breeze may bring subtle shifts or news, while powerful wind can suggest instability, transition, or an environment that is already changing around you.',
    positiveEn: 'Adaptability can help you make good use of a changing situation.',
    negativeEn: 'Scattered focus may leave your plans vulnerable to outside movement.',
    adviceEn: 'Notice which way conditions are changing and adjust your pace without abandoning your core intention.',
    themesEn: ['Change', 'News', 'Flexibility'],
  },
]
