export type AppPage =
  | 'tarot'
  | 'horoscope'
  | 'almanac'
  | 'cybermerit'
  | 'bazi'
  | 'divination'
  | 'dream'
  | 'fengshui'
  | 'auspicious'
  | 'numberenergy'
  | 'luckycolor'
  | 'qimen'
  | 'nametest'
  | 'ziwei'
  | 'shengxiao'
